repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.14.1
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
